# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java
env: flex

automatic_scaling:
  max_num_instances: 1

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"


env_variables:
  OPENAI_API_KEY: "sk‑proj‑dB2gt4j5xFGqjRf8raQCSkytLrHDY0K2qWPM1y2UYZMnK2NlLuQN6FqCiv2ObPh8IVAoucHj9pT3BlbkFJEYI4Tg4d8aeyLHaS5UAGIRCWHtHn0VlY1GqYkfJHKUEFDv0iI-4mg3zjd97vQcW8EHAfKZjFYA"
